UEGMobile\ArduinoOTAServerBundle\Entity\OTADeviceMac:
    type: entity
    table: aotas_device_mac
    repositoryClass: UEGMobile\ArduinoOTAServerBundle\Repository\OTADeviceMacRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    indexes:
      mac_index:
        columns: [ mac ]

    fields:
        mac:
            type: string
            length: '64'
        mode:
            type: string
            length: '16'
            nullable: false
        createdAt:
            type: datetime
            column: created_at
            options:
              default: CURRENT_TIMESTAMP
        updatedAt:
            type: datetime
            column: updated_at
            options:
              default: CURRENT_TIMESTAMP
        active:
            type: boolean
            nullable: false
            options:
              default: false
    manyToOne:
        program:
            targetEntity: OTAProgram
            joinColumn:
                name: program
                referencedColumnName: id
    lifecycleCallbacks: {  }
