sudo: false

language: php

php:
  - 7.1
    
matrix:
  fast_finish: true
  include:
    # Test against Symfony LTS versions
    - php: 7.1
      env: SYMFONY_VERSION="2.8.*" DEPENDENCIES=stable
    - php: 7.1
      env: SYMFONY_VERSION="3.4.*" DEPENDENCIES=stable

before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:"$SYMFONY_VERSION"; fi
    - COMPOSER_MEMORY_LIMIT=-1 composer install -v --prefer-dist --no-interaction
  
script:
    - composer validate
