<?php

namespace UEGMobile\ArduinoOTAServerBundle\Repository;

/**
 * OTABinaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OTABinaryRepository extends \Doctrine\ORM\EntityRepository
{
}
