<?php

namespace UEGMobile\ArduinoOTAServerBundle\Repository;

/**
 * OTADeviceMacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OTADeviceMacRepository extends \Doctrine\ORM\EntityRepository
{
}
