language: node_js
node_js:
  - 4
  - 5
  - 6

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 

before_install:
  - npm install -g grunt-cli

install:
  - npm prune && npm install
  - node_modules/protractor/bin/webdriver-manager update --standalone --firefox
  - node_modules/protractor/bin/webdriver-manager start 2>&1 &  
  - sleep 3

script:
  - grunt test

cache:
  directories:
    - node_modules
